import { useLocation, useNavigate } from "react-router-dom";
import {
  CheckCircle,
  XCircle,
  RotateCcw,
  Home,
  FileText
} from "lucide-react";

import "../static/ExamResult.css";
import { Download } from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function ExamResult() {

  const navigate = useNavigate();
  const { state } = useLocation();

  if (!state) {
    return (
      <div className="result-container">
        <h2>No Result Found</h2>

        <button
          onClick={() => navigate("/dashboard")}
        >
          Go Dashboard
        </button>
      </div>
    );
  }

  const {
    subject,
    sessionId,
    score,
    totalQuestions,
    answeredQuestions,
    timeTaken
  } = state;

  const correct = score;

  const answered = answeredQuestions.length;

  const wrong = answered - correct;

  const skipped = totalQuestions - answered;

  const percentage = Math.round(
    (correct / totalQuestions) * 100
  );

  const passed = percentage >= 50;

  const minutes = Math.floor(timeTaken / 60);

  const seconds = timeTaken % 60;

  const downloadPDF = () => {

    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text(
        "AI Interview Preparation",
        105,
        18,
        { align: "center" }
    );

    doc.setFontSize(16);
    doc.text(
        "Exam Result Report",
        105,
        28,
        { align: "center" }
    );

    doc.setFontSize(12);

    doc.text(
        `Subject : ${subject || "N/A"}`,
        20,
        45
    );

    doc.text(
        `Score : ${correct}/${totalQuestions}`,
        20,
        55
    );

    doc.text(
        `Percentage : ${percentage}%`,
        20,
        65
    );

    doc.text(
        `Status : ${passed ? "PASS" : "FAIL"}`,
        20,
        75
    );

    autoTable(doc, {

        startY: 90,

        head: [["Metric", "Value"]],

        body: [

            ["Correct", correct],

            ["Wrong", wrong],

            ["Skipped", skipped],

            ["Answered", answered],

            ["Time Taken",
            `${minutes}:${seconds.toString().padStart(2,"0")}`],

            ["Accuracy", `${percentage}%`]

        ]

    });

    const finalY = doc.lastAutoTable.finalY + 20;

    doc.setFontSize(15);

    doc.text(
        "AI Feedback",
        20,
        finalY
    );

    doc.setFontSize(12);

    let feedback = "";

    if (percentage >= 80) {

        feedback =
        "Excellent performance. You are interview ready.";

    }

    else if (percentage >= 60) {

        feedback =
        "Good performance. Improve weak topics.";

    }

    else {

        feedback =
        "Need more practice. Revise the fundamentals.";

    }

    doc.text(
        feedback,
        20,
        finalY + 10
    );

    doc.setFontSize(10);

    doc.text(
        "Generated by AI Interview Preparation",
        105,
        285,
        { align: "center" }
    );

    doc.save(
        `Exam_Result_${subject || "Exam"}.pdf`
    );

};


  return (

    <div className="result-container">

      <div className={`result-card ${passed ? "pass" : "fail"}`}>

        {
          passed
            ? <CheckCircle size={70} color="#22c55e"/>
            : <XCircle size={70} color="#ef4444"/>
        }

        <h1>
          {passed ? "Congratulations!" : "Keep Practicing!"}
        </h1>

        <p>
          {passed
            ? "You passed this assessment."
            : "You can improve with more practice."}
        </p>

        <div className="result-circle">

          <h2>

            {percentage}%

          </h2>

          <p>

            {correct} / {totalQuestions}

          </p>

        </div>

      </div>

      <div className="stats-grid">

        <div className="stat-card">

          <h3>Correct</h3>

          <h2>{correct}</h2>

        </div>

        <div className="stat-card">

          <h3>Wrong</h3>

          <h2>{wrong}</h2>

        </div>

        <div className="stat-card">

          <h3>Skipped</h3>

          <h2>{skipped}</h2>

        </div>

        <div className="stat-card">

          <h3>Time</h3>

          <h2>

            {minutes}:{seconds.toString().padStart(2,"0")}

          </h2>

        </div>

      </div>

      <div className="result-progress">

        <h3>Performance</h3>

        <div className="progress-bar">

          <div

            className="progress-fill"

            style={{

              width:`${percentage}%`

            }}

          />

        </div>

      </div>

      <div className="ai-feedback">

        <h2>

          AI Performance Analysis

        </h2>

        <p>

          Accuracy :

          <b>

            {" "}
            {percentage}%

          </b>

        </p>

        <p>

          You answered

          <b>

            {" "}
            {correct}

          </b>

          {" "}questions correctly.

        </p>

        {

          percentage >= 80 &&

          <p className="excellent">

            Excellent performance. Ready for interviews.

          </p>

        }

        {

          percentage >= 60 && percentage < 80 &&

          <p className="good">

            Good performance. Revise weak concepts.

          </p>

        }

        {

          percentage < 60 &&

          <p className="poor">

            Need more practice. Focus on fundamentals.

          </p>

        }

      </div>
        
      <div className="result-buttons">

         <button
    className="review-btn"
    onClick={()=>

        navigate("/review-exam",{

            state:{

                sessionId

            }

        })

    }
 >

    Review Answers
       </button>
        <button
    className="download-btn"
    onClick={ downloadPDF }
    >
    <Download size={18}/>
    Download PDF
</button>

        <button

          className="retry-btn"

          onClick={() => navigate(-1)}

        >

          <RotateCcw size={18}/>

          Retake Exam

        </button>

        <button

          className="home-btn"

          onClick={() => navigate("/dashboard")}

        >

          <Home size={18}/>

          Dashboard

        </button>
        

      </div>

    </div>

  );

}